"""add assign fields

Revision ID: 4223b6b1b5c2
Revises: 645810cb0c0e
Create Date: 2026-05-05 15:59:08.848255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4223b6b1b5c2'
down_revision = '645810cb0c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['assigned_to'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_assign', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_assign')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_by')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###
