"""fix assignment architecture

Revision ID: 74e238d575ce
Revises: 2fe571aa5b21
Create Date: 2026-05-07 18:37:43.648884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e238d575ce'
down_revision = '2fe571aa5b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ticket_assigned_to_fkey'), type_='foreignkey')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('assigned_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('ticket_assigned_to_fkey'), 'user', ['assigned_to'], ['id'])

    op.drop_table('ticket_assignment')
    # ### end Alembic commands ###
