"""cascade delete for ticket relations

Revision ID: 939c60d5f716
Revises: 7c98429e8b54
Create Date: 2026-05-08 15:40:58.485077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939c60d5f716'
down_revision = '7c98429e8b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comments_ticket_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ticket', ['ticket_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ticket_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ticket_assignment_ticket_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ticket', ['ticket_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ticket_assignment_ticket_id_fkey'), 'ticket', ['ticket_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comments_ticket_id_fkey'), 'ticket', ['ticket_id'], ['id'])

    # ### end Alembic commands ###
